import type { Post, User } from '../types';

export const DUMMY_USERS: User[] = [
  {
    id: 'u1',
    name: 'Nithish Kanna',
    email: 'nithishkanna@kce.ac.in',
    role: 'student',
    department: 'Computer Science and Technology',
    rollNumber: '21CST001',
    avatar: null,
    createdAt: '2024-08-01T00:00:00Z',
  },
  {
    id: 'u2',
    name: 'Dr. Priya Ramasamy',
    email: 'priya.r@kce.ac.in',
    role: 'faculty',
    department: 'Electronics and Communication Engineering',
    rollNumber: 'FAC001',
    avatar: null,
    createdAt: '2020-06-01T00:00:00Z',
  },
  {
    id: 'u3',
    name: 'Arjun Balaji',
    email: 'arjun.b@kce.ac.in',
    role: 'student',
    department: 'Mechanical Engineering',
    rollNumber: '22MECH015',
    avatar: null,
    createdAt: '2023-08-15T00:00:00Z',
  },
  {
    id: 'u4',
    name: 'Kavitha Sundaram',
    email: 'kavitha.s@kce.ac.in',
    role: 'alumni',
    department: 'Information Technology',
    rollNumber: '19IT042',
    avatar: null,
    createdAt: '2019-06-01T00:00:00Z',
  },
  {
    id: 'u5',
    name: 'Prof. Suresh Babu',
    email: 'suresh.b@kce.ac.in',
    role: 'faculty',
    department: 'Civil Engineering',
    rollNumber: 'FAC002',
    avatar: null,
    createdAt: '2015-01-01T00:00:00Z',
  },
  {
    id: 'u6',
    name: 'Meena Lakshmi',
    email: 'meena.l@kce.ac.in',
    role: 'staff',
    department: 'Library & Information Services',
    rollNumber: 'STF001',
    avatar: null,
    createdAt: '2021-03-01T00:00:00Z',
  },
];

export const DUMMY_POSTS: (Post & { author: User })[] = [
  {
    id: 'p1',
    authorId: 'u2',
    author: DUMMY_USERS[1],
    content: '📢 Attention CST students! The Internal Assessment 2 results have been uploaded to the college portal. Please check your scores and meet your faculty advisor if you have any concerns before the deadline on Friday.\n\nAll the best for your semester exams! 💪',
    mediaUrl: null,
    likesCount: 87,
    commentsCount: 14,
    createdAt: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
    isLiked: false,
  },
  {
    id: 'p2',
    authorId: 'u1',
    author: DUMMY_USERS[0],
    content: 'Just finished setting up our final-year project demo environment! 🚀 We\'re building an IoT-based smart irrigation system for the campus garden. Presenting at the National Tech Fest next week — wish us luck! 🌱\n\n#FinalYearProject #KCE #IoT',
    mediaUrl: null,
    likesCount: 124,
    commentsCount: 23,
    createdAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    isLiked: true,
  },
  {
    id: 'p3',
    authorId: 'u4',
    author: DUMMY_USERS[3],
    content: 'Coming back to the KCE campus after 3 years! The new lab block looks incredible. So proud to be a Karpagamian 🎓❤️\n\nFor juniors: placement season is starting soon. Start your DSA prep NOW. Don\'t wait. Trust me.',
    mediaUrl: null,
    likesCount: 203,
    commentsCount: 41,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    isLiked: false,
  },
  {
    id: 'p4',
    authorId: 'u5',
    author: DUMMY_USERS[4],
    content: '📚 Reminder: The Department of Civil Engineering is hosting a guest lecture on "Sustainable Construction Practices in Urban India" this Thursday at 10:30 AM in Seminar Hall B. Attendance is open to all departments.\n\nGuest speaker: Ar. Ramesh Venkat (IIT Madras alumnus)',
    mediaUrl: null,
    likesCount: 56,
    commentsCount: 8,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 7).toISOString(),
    isLiked: false,
  },
  {
    id: 'p5',
    authorId: 'u3',
    author: DUMMY_USERS[2],
    content: 'The WiFi in Block C labs has been down since this morning. Has anyone reported it? Already seeing 5 people struggling with their simulation work. Thought this new connection was supposed to fix things 😤',
    mediaUrl: null,
    likesCount: 312,
    commentsCount: 67,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 9).toISOString(),
    isLiked: true,
  },
  {
    id: 'p6',
    authorId: 'u6',
    author: DUMMY_USERS[5],
    content: '📖 New arrivals in the Central Library! We\'ve received over 200 new textbooks across all engineering disciplines, including the latest edition of Sedra/Smith and Cormen\'s CLRS algorithms book.\n\nAvailable from Monday. Borrow limit increased to 5 books per student this semester.',
    mediaUrl: null,
    likesCount: 44,
    commentsCount: 5,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    isLiked: false,
  },
];

export const TRENDING_TOPICS = [
  { tag: 'InternalAssessment', posts: 128 },
  { tag: 'TechFest2026', posts: 94 },
  { tag: 'Placements2026', posts: 217 },
  { tag: 'CampusWifi', posts: 83 },
  { tag: 'FinalYearProject', posts: 61 },
];

export const UPCOMING_EVENTS = [
  { title: 'Civil Dept Guest Lecture', date: 'Thu, Apr 7', time: '10:30 AM', venue: 'Seminar Hall B', category: 'Academic' },
  { title: 'National Tech Fest 2026', date: 'Sat, Apr 9', time: 'All Day', venue: 'Main Campus', category: 'Fest' },
  { title: 'Placement Drive — TCS', date: 'Mon, Apr 11', time: '9:00 AM', venue: 'Placement Cell', category: 'Career' },
  { title: 'Alumni Networking Meet', date: 'Fri, Apr 14', time: '5:00 PM', venue: 'Auditorium', category: 'Networking' },
  { title: 'Sports Day 2026', date: 'Wed, Apr 19', time: '8:00 AM', venue: 'Grounds', category: 'Sports' },
  { title: 'CST Hackathon v1.0', date: 'Sat, Apr 23', time: '24 Hours', venue: 'Lab 4', category: 'Academic' },
];

export const EXPLORE_LINKS = [
  { label: 'College Portal', icon: '📋', color: '#A6192E' },
  { label: 'Library', icon: '📖', color: '#1A2254' },
  { label: 'Hostel Pass', icon: '🏠', color: '#4A5FD9' },
  { label: 'Exam Results', icon: '📊', color: '#28A745' },
  { label: 'Timetable', icon: '📅', color: '#FFC107' },
  { label: 'Bus Routes', icon: '🚌', color: '#2a3578' },
  { label: 'Mess Menu', icon: '🍽️', color: '#e67e22' },
  { label: 'Emergency', icon: '📞', color: '#c0392b' },
];
